### ISSUE TITLE
Intact genes have pre mature stop condon 

### ISSUE THREAD

**Issue by lizihe21** [hillerlab/TOGA#15]
Hi,@kirilenkobm
I have finished the pipeline on my own dataset. And the result is awsome, about 80% ref gene can be annotated correctly. Thanks for your great work.
There are still some problems in the results. About 4000 projection annotated as intact actually has pre mature stop codon or lack of start codon. Here is an example from the cesar_results.txt:
 >transcript:ENSBTAT00000025161.19 | CODON | REFERENCE
ATG CCA CCC TGC CAG GTT GTC ACA GAG CAC --- GAG AAG 
>transcript:ENSBTAT00000025161.19 | CODON | QUERY
--- CCA CCC TGC CAG GTC GTC ACA GAG CAC XXX --- AAG 
In many ways, this gene should be regarded as pseudogene or lost. But toga classify it as intact. Is there something wrong with the class module or you just do it for some reason?

**Comment by kirilenkobm** [comment]
Hi @lizihe21,

Nice to hear that you got some results.

About the classification issues: gene loss detector implemented in TOGA is rather conservative, so it requires strong evidence to decide that gene/transcript is lost.
A single inactivating mutation is not enough (it could be an assembly mistake, it could happen in a non-conservative exon, and so on). Mutations that appear close to C and N termini (more precisely, first and last 10% of the CDS in TOGA) are not treated as inactivating (I'd check whether this is the case for your 4000 projections) because these regions are under weaker evolutionary constraints. Inactivations in these regions are very unlikely to kill the gene.
Lack of the start codon in the expected position also provides very weak evidence for gene inactivation. It could be shifted up or downstream. Technically, TOGA detects this sort of mutation but doesn't use it for classification.

In your example, the premature stop codon is very close to the CDS end - CESAR just inserted another AAG codon after it. (why?) In practice, this particular mutation means that the protein will be 2 aa shorter; most likely, this is not an issue (unless this is some localization signal, but this is a completely different story).

**Comment by lizihe21** [comment]
Thanks for quickly responding. So it means that TOGA will be tolerant to the mutation at both ends of gene. But the problem is still here. The case I put firstly is at the start of the gene rather than at the end. In this case, cesar didn't find the ATG start codon of gene and then ignore the premature stop codon before the AAG. That is  a more significant problem than a premature stop codon in the end. If there is no new start codon, the gene may just die.

**Comment by yuzhenpeng** [comment]
> Thanks for quickly responding. So it means that TOGA will be tolerant to the mutation at both ends of gene. But the problem is still here. The case I put firstly is at the start of the gene rather than at the end. In this case, cesar didn't find the ATG start codon of gene and then ignore the premature stop codon before the AAG. That is a more significant problem than a premature stop codon in the end. If there is no new start codon, the gene may just die.

first and last 10% of the CDS in TOGA are not treated as inactivating.

**Comment by MichaelHiller** [comment]
Hi, 
correct, if there is no ATG following a stop codon at the 5' end, then there is no way to translate the gene. 
But what is possible is that there is potentially a new lineage-specific exon in the first intron and this new exon could have an inframe ATG. Such cases are not detectable for CESAR / TOGA. 

Bogdan has clear data showing that for a large set of conserved genes, real inactivating mutations occur most frequent at the N and C terminus of the encoded protein. Therefore, we decided to not call genes as lost if they only have inactivating mutations in the first / last 10%. 

But of course, as for any threshold one sets, there are always individual cases, where this threshold gives the wrong answer. In your case, the gene with the missing ATG could really be lost. 

Michael

**Comment by yuzhenpeng** [comment]
Hi,

How to prepare a bed12-formatted file as a reference genome annotation.

**Comment by lizihe21** [comment]
> Hi,
> 
> How to prepare a bed12-formatted file as a reference genome annotation.

Hi
You can use gffread to convert gff to bed12. There are two tools in ucsc tools gff3ToGenePred and genePredToBed which can be used to do so

**Comment by lizihe21** [comment]
> correct, if there is no ATG following a stop codon at the 5' end, then there is no way to translate the gene.

Hi
I just added a filtering step after TOGA to use the result in gene prediction. This works well now.
Thanks for all of your work.
Leo

**Comment by yuzhenpeng** [comment]
> > Hi,
> > How to prepare a bed12-formatted file as a reference genome annotation.
> 
> Hi
> You can use gffread to convert gff to bed12. There are two tools in ucsc tools gff3ToGenePred and genePredToBed which can be used to do so

could I used the human genome annotation in supply/hg38.v35.for_toga.bed in TOGA？Is it correct (or completed) for human？

@MichaelHiller @lizihe21
