### ISSUE TITLE
Some genes lost in the loss_summ_data.tsv

### ISSUE THREAD

**Issue by txfc** [hillerlab/TOGA#154]
Hi, thank your great job!
 I wanted to explore gene loss among some birds. I used the chicken assembly as the reference from TOGAinput. However, the query assembly is very fragmented, the scaffold N50 only is 47kb. When I checked the `loss_summ_data.tsv`, I could not find some genes in the file, but these genes were annotated in the chicken reference. I compared some other birds that have a better assembly level, and this problem did not happen.
For example, this is a part of loss_summ_data.tsv from low-quality assembly. I can not find the gene _A1CF_ and _AACS_.
```
GENE	A4GALT	I
GENE	A4GNT	I
GENE	AAAS	UL
GENE	AADAC	I
GENE	AADAT	I
GENE	AAGAB	I
GENE	AAK1	I
GENE	AAMDC	L
GENE	AAMP	PI
GENE	AANAT	I
```
This is a part of loss_summ_data.tsv from high-quality assembly. The _A1CF_ and _AACS_ are present.
```
GENE	A1CF	I
GENE	A4GALT	I
GENE	A4GNT	I
GENE	AAAS	UL
GENE	AACS	I
GENE	AADAC	I
GENE	AADAT	I
GENE	AAGAB	I
GENE	AAK1	I
GENE	AAMDC	L
GENE	AAMP	I
GENE	AANAT	I

```
so I want to know how to classify these genes lost in the file.
This is the information about these genes in the low-quality orthology_classification.tsv
```
AACS	AACS_rna-NM_001006184.1	None	None	one2zero
AACS	AACS_ENSGALT00000004577.6	None	None	one2zero
A1CF	A1CF_rna-XM_015278705.2	None	None	one2zero
A1CF	A1CF_rna-XM_421561.6	None	None	one2zero
A1CF	A1CF_rna-XM_003641458.4	None	None	one2zero
```
so I want to know why these genes were lost in the file.
Should these genes be classified as missing or something else?

Thank you!

**Comment by MichaelHiller** [comment]
I assume that these two genes do not align at all or are not even spanned by a chain. In this case, they should be classified as missing, but sometimes when there is no chain, TOGA can't even do the first step of chain classification. 

Can you pls look into the genes_rejection_reason.tsv  file if you find an entry for these 2? 

Unless you are certain that both genes are really not present in your genome (not just in a fragmented and incomplete assembly), I would not call them lost. 

If you send me which assembly it is, I can have a look in the genome browser.

**Comment by txfc** [comment]
@MichaelHiller 
Both A1CF and AACS are listed as having 'fragment chains overlap' in the genes_rejection_reason.tsv file.
The assembly ID I use in the task is GCA_000695765.1.

**Comment by MichaelHiller** [comment]
Here is how A1CF looks like. There are 3 chains that represent orthologous pieces in the query (chain ID 10923, 55354, 16104)
![image](https://github.com/hillerlab/TOGA/assets/8644098/d5cdf3eb-bcfd-4181-9e2a-ae145c24b156)

TOGA seems to correctly recognize the gene 
![image](https://github.com/hillerlab/TOGA/assets/8644098/9ee569e6-33bf-4257-b4d5-4808b587419b)

**Comment by MichaelHiller** [comment]
Here is the other one. Chain 11002 and 16122
![image](https://github.com/hillerlab/TOGA/assets/8644098/581dd3d3-d6a8-4859-a6c1-08897971548e)

g ENSGALT00000004577 query_annotation.bed orthology_classification.tsv loss_summ_data.tsv 
query_annotation.bed:JJRI01058356	2125	17610	AACS_ENSGALT00000004577.6.-1	1000	-	2125	17610	255,160,120	4	98,114,121,104,0,7892,10942,15381,
query_annotation.bed:KK807348	1701	20028	AACS_ENSGALT00000004577.6.-1	1000	+	1701	20028	255,160,120	13	115,82,148,81,125,65,123,114,126,70,59,203,138,	0,798,1528,5743,6940,9735,9978,11449,12015,13700,14694,15609,18189,
orthology_classification.tsv:AACS	AACS_ENSGALT00000004577.6	reg_5051	AACS_ENSGALT00000004577.6.-1	one2one
loss_summ_data.tsv:PROJECTION	AACS_ENSGALT00000004577.6.-1	UL
loss_summ_data.tsv:TRANSCRIPT	AACS_ENSGALT00000004577.6	UL

This one is UL because there is a TGA in a middle exon. And note that the first exon is not covered by any chain --> this exon is missing. 
![image](https://github.com/hillerlab/TOGA/assets/8644098/c7cd1a6f-e0da-46e6-beeb-b7f271039496)

**Comment by txfc** [comment]
Thank you!
I have understood your explanation about these two genes.
So I want to know what's wrong with my TOGA task. I can not find any information containing these two genes in the query_annotation.bed,orthology_classification.tsv, and loss_summ_data. tv. but you can get it.
I check this log from TOGA, and the end is that.
```
#### STEP 11: Cleanup: merge parallel steps output files
!!2915 CESAR wrapper commands failed
```
This is my command to run TOGA
`/path/TOGA/toga.py /path/chain_file/chicken.brown_roatelo.final.chain /path/TOGA/TOGAInput/chicken_galGal6/toga.transcripts.bed /path/TOGA/TOGAInput/chicken_galGal6/gallus6a.sm.2bit /path/2bit/brown_roatelo_renamed_chrom.2bit --kt --pn  /path/TOGA/chicken.brown_roatelo -i /path/TOGA/TOGAInput/chicken_galGal6/toga.isoforms.tsv --cb 6,10 --cjn 250 --ms`
My server has 256 cores and 1 TB of memory.
How can I get the same result as you?

**Comment by MichaelHiller** [comment]
Maybe this is related to the parameter that enables joining fragmented genes. We internally always used this, but somehow this was not the default. 
In TOGA 1.1.3, we 
"Removed -f/--fragmented_genome flag from toga.py CLI - the "assemble transcript from fragments" feature is enabled by default. Please use --disable_fragments_joining/--dfj option to disable this feature."

Is this the explanation? Otherwise I don't know

**Comment by txfc** [comment]
Thank you!
After using your command, the loss_summ_data.tsv contains all of the annotated genes in chickens.
