### ISSUE TITLE
bed to gff

### ISSUE THREAD

**Issue by DiegoSafian** [hillerlab/TOGA#67]
Hi,

I remember there was an "issue" asking about how to transform the query_annotation.bed into gft or gff3. There used to be a response here but it was deleted. Could you please prove this infor again??

I remember GenomeTools was needed. 

Thanks

**Comment by MichaelHiller** [comment]
Hi Diego, 

you need the UCSC kent binaries to first convert bed to genePred and then to gtf. 

bedToGenePred query_annotation.bed stdout | genePredToGtf stdin query_annotation.gtf 

genePredToGtf has some options that could be useful.
genePredToGtf - Convert genePred table or file to gtf.
usage:
   genePredToGtf database genePredTable output.gtf
If database is 'file' then track is interpreted as a file
rather than a table in database.
options:
   -utr - Add 5UTR and 3UTR features
   -honorCdsStat - use cdsStartStat/cdsEndStat when defining start/end
    codon records
   -source=src set source name to use
   -addComments - Add comments before each set of transcript records.
    allows for easier visual inspection
Note: use a refFlat table or extended genePred table or file to include
the gene_name attribute in the output.  This will not work with a refFlat
table dump file. If you are using a genePred file that starts with a numeric
bin column, drop it using the UNIX cut command:
    cut -f 2- in.gp | genePredToGtf file stdin out.gp

**Comment by kirilenkobm** [comment]
All topics related to "how can I convert TOGA's X into Y" shall be documented on this wiki page: https://github.com/hillerlab/TOGA/wiki/Converting-TOGA-results-into-different-formats
