### ISSUE TITLE
Stalling during run.

### ISSUE THREAD

**Issue by LeebanY** [hillerlab/TOGA#7]
Hi @kirilenkobm,

Thanks for the cool program first of all.

I've been trying to run TOGA on my dataset and I ran the following command:

./toga.py FISH_DATA/A_B.chain FISH_DATA/A.augustus.transcripts.BED12.bed FISH_DATA/A.fasta.2bit FISH_DATA/B.fasta.2bit --kt --pn FISH_COMPARATIVE_TOGA --nc nextflow_config_files --cjn 50 --cb 5,10,50 --ms

The pipeline works up until STEP 2 where nextflow is called and then it exhibits some strange behaviour. All the jobs were submitted to the cluster (SGE, not slurm, but I adjusted this as you suggest in the instructions), and suddenly all the jobs died after maybe a few minutes running, but TOGA continued to run indefinitely before I killed it. I have no error messages so I'm not sure if this is desired behaviour, but I had no log updates from TOGA for 24hours, as well as no intermediate files, so I imagine something is going wrong, I'm just not sure what. I'm sorry this is not more informative, but let me know if I can provide anymore details if I've missed anything out.

Thanks,
Leeban

**Comment by kirilenkobm** [comment]
Hi @LeebanY,

Thank you for reporting that; that's really interesting.
This is definitely not the desired behavior.
Actually, I would expect the jobs to be completed after a few minutes, not dead. Usually, if there is some systematic problem with the dataset, all jobs die immediately. 
Also, if any of the cluster jobs crashed, TOGA should halt itself.
24 hours is too much at this step. 

I would ask the following to clarify this case:
1) How did you know that all the jobs died since there are no error messages?
2) Please send me your cluster configuration files.
3) Did you try to run TOGA on the test samples? For example like this:
./toga.py test_input/align_micro_sample.chain test_input/annot_micro_sample.bed test_input/hg38.micro_sample.2bit test_input/q2bit_micro_sample.2bit --pn micro_test
It will take a couple of minutes. If everything is fine then please try this (previous one runs on CPU, this uses nextflow):
./toga.py test_input/align_micro_sample.chain test_input/annot_micro_sample.bed test_input/hg38.micro_sample.2bit test_input/q2bit_micro_sample.2bit --pn micro_test --nc nextflow_config_files
If the second one crashes then there is some issue with cluster configuration: maybe on the nextflow level, maybe the problem sits deeper.

Alternatively, if you have 2bit files for human (hg38) and mouse (mm10) assemblies you could run a bit more serious test:
./toga.py test_input/hg38.mm10.chr11.chain test_input/hg38.genCode27.chr11.bed  HUMAN.2BIT MOUSE.2BIT --pn test_out -i supply/hg38.wgEncodeGencodeCompV34.isoforms.txt --cb 3,5 --k  --nc nextflow_config_files
(I would not recommend to run this test without cluster simply because it will take too long).
I hope this will help us to understand what exactly is going on.

Best,
Bogdan

**Comment by lizihe21** [comment]
> Hi @kirilenkobm,
> 
> Thanks for the cool program first of all.
> 
> I've been trying to run TOGA on my dataset and I ran the following command:
> 
> ./toga.py FISH_DATA/A_B.chain FISH_DATA/A.augustus.transcripts.BED12.bed FISH_DATA/A.fasta.2bit FISH_DATA/B.fasta.2bit --kt --pn FISH_COMPARATIVE_TOGA --nc nextflow_config_files --cjn 50 --cb 5,10,50 --ms
> 
> The pipeline works up until STEP 2 where nextflow is called and then it exhibits some strange behaviour. All the jobs were submitted to the cluster (SGE, not slurm, but I adjusted this as you suggest in the instructions), and suddenly all the jobs died after maybe a few minutes running, but TOGA continued to run indefinitely before I killed it. I have no error messages so I'm not sure if this is desired behaviour, but I had no log updates from TOGA for 24hours, as well as no intermediate files, so I imagine something is going wrong, I'm just not sure what. I'm sorry this is not more informative, but let me know if I can provide anymore details if I've missed anything out.
> 
> Thanks,
> Leeban

I met this problem too. And I found it happened when I called nextflow in python3. When I changed to python2 or called nextflow directly in bash, it works well. But in python3 , no matter 3.7 or 3.8 and running in foreground or background, it just failed and resubmit job forever until I close the terminal.  But I didn't found the way to solve it. Maybe someone can. My python is installed in annaconda2 environment.

**Comment by kirilenkobm** [comment]
Hopefully is fixed in the recent TOGA version.
