### ISSUE TITLE
nextflow config file cpu number setting in accordance with memory requested

### ISSUE THREAD

**Issue by XieHongX** [hillerlab/TOGA#73]
Hi,
I have a case-specific issue here. I am trying to run TOGA on a slurm based cluster, but when requesting for resources, the cluster has a limit of CPU:memory = 1:3GB, which means if I ask for 1 cpu, I cannot ask for more than 3GB memory. Therefore, I tried modifying the "process.cpus" in the "call_cesar_config_template.nf" file. The purpose is to keep a CPU:memory = 1:3GB ratio according to memory needed. I made several attempts such as: 
process.cpus = "${${${_MEMORY_}/3}+1}" 
to get an integer that will fit the ratio but not being successful. I don't know the language used here. 
This may seem a naive question, do you have a solution?

best
Hongxin

**Comment by kirilenkobm** [comment]
Hi,

this is definitely not a naïve, but rather a complex question.
Nextflow uses Groovy, but its config files are static - do not allow inserting dynamic computations in them.

I need to think about this;
But yeah, the best solution would be to somehow discuss this limitation, otherwise it is clearly a waste of CPU resources - CESAR utilizes a single core, but can occupy a wealth of RAM

**Comment by kirilenkobm** [comment]
Hi @XieHongX 

I am sorry, but I think the issue is very system-dependent and lies out of the TOGA implementation scope.

Something to be documented later.
https://github.com/hillerlab/TOGA/wiki/Installation-and-configuration

On the bright side, TOGA version `1.1.5` will provide a native and simple way to implement custom parallelization strategies. https://github.com/hillerlab/TOGA/blob/master/parallel_jobs_manager.py
(this module is not yet included in the main pipeline, but will be)
Maybe, this will help.

**Comment by XieHongX** [comment]
Thank you anyway! I will then run TOGA in local mode. Glad to hear there will be an updated parallelisation pipeline
