### ISSUE TITLE
TypeError: NoneType.__new__(X): X is not a type object (NoneType)

### ISSUE THREAD

**Issue by Ryuto-sanno** [hillerlab/TOGA#8]
Hi @kirilenkobm,

Thanks for the cool program first of all.
I've been trying to run TOGA on my dataset and I ran the following command:

`./toga.py [input.chain] [reference.bed12] [reference.2bit] [target.2bit] --kt --pn test --cb 3,5 --cjn 500 --ms --no_chain_filter`

The pipeline works up until STEP 3. But, TOGA gave me  an error message.

`TypeError: NoneType.__new__(X): X is not a type object (NoneType)`

 So I imagine something is going wrong, I'm just not sure what. I'm sorry but please tell me the solution.

Thanks,
Ryuto

**Comment by kirilenkobm** [comment]
Hi @Ryuto-sanno,

Thank you a lot, and sorry for the long silence.
Briefly, in this case, joblib fails to load the trained XGBoost model.
My colleague recently ran into the same issue, so I was able to reproduce and resolve it.
It was not the easiest issue because googling this problem didn't give me any relevant results.

As I understand, the problem was that Python interpreters that (i) she used and (ii) that was used to train the models had a bit different versions of numpy and scikit-learn. Joblib and xgboost versions were the same.
When I downgraded her scikit-learn and numpy, the issue got solved.

Please check that you used exactly the same interpreters with exactly the same libraries to train and load the models. In my colleague's case, numpy and scikit-learn were installed at least twice (globally for all users on the cluster and her personal installations). 

Best,
Bogdan

**Comment by kirilenkobm** [comment]
Also:

maybe your Python infrastructure is very complex; then I would recommend trying virtual environments.
Besides, I'm planning to pack TOGA into a singularity container (I guess till the mid/end of January, I'll be able to finish this).
This should eliminate issues like this.
