### ISSUE TITLE
Adding RNA sequence data

### ISSUE THREAD

**Issue by Alchimic007** [hillerlab/TOGA#82]
Hello, just wanted to ask is it possible to add RNA sequence data in TOGA, and if it is possible, how can I do that. Thank you

**Comment by Alchimic007** [comment]
Thank you for contacting with me so fast. I would like to use RNA sequence for detecting target-specific transcript sequences

**Comment by kirilenkobm** [comment]
Could you please provide additional details regarding the input data you plan to use, and its format? This information will help to determine whether TOGA is the right tool for your project or if there might be a way to adjust it to better suit your requirements.

For your reference, TOGA typically requires genome sequences for the reference and query genomes in 2bit format, reference genome annotation in bed12 format, and pairwise genome alignment between the reference and the query.

If your issue is still relevant, feel free to reopen this discussion with the requested details. We're here to help and look forward to assisting you further.
