### ISSUE TITLE
Filtering bed output

### ISSUE THREAD

**Issue by danielle-khost** [hillerlab/TOGA#90]
Hi there!
Thanks for developing this great tool! I had a question regarding the filtering out the query_annotation.bed file that is produced by TOGA. My input number of reference transcripts was about 31k, whereas the query annotation produced is about 101k, which seems too high. Digging thought the output, I found the following:

![image](https://github.com/hillerlab/TOGA/assets/52081103/7cdffd3f-4b3a-4ed8-bf9f-176e30096485)

43k transcripts and 13k one2one genes makes a bit more sense, based on our expectations. However, I couldn't find anything in the documentation about what this filter step is, nor whether that output is saved somewhere? I did try filtering out small single exon transcripts, but found that only removed about 10k transcripts. Also, any advice you have about filtering the output in general or why so many more orthologous chains are being created would be super helpful!

Thanks,
Danielle

**Comment by MichaelHiller** [comment]
Hi Danielle, 

this is a good point and I think in general the following t

Our query_annotation.bed also contains genes and transcripts classified as lost. 
Such transcripts can either be the real remnants of a lost gene or inactive/incomplete copies of an existing gene. 
Since most lost genes are still detectable in mammalian genomes (complete gene deletion as in bacteria is rather rare), we thought it is a good idea to also list the loci of inactivated genes in the annotation. 
E.g. I find it helpful to see the inactivated Gulo in the human genome
![image](https://github.com/hillerlab/TOGA/assets/8644098/faf6fd61-03b4-4848-a6e1-ce45a2bebc3c)

[[ Another detail, because you asked about orthologous chains. TOGA will also consider spanning chains as potential candidates where a gene can be located in the query genome. While these chains typically don't align the gene, in a few edge cases, TOGA may still detect a few or a single exon and annotate another lost transcript.]]

If you want to extract the transcripts classified as say Intact (I), Partially Intact (PI) or Uncertain Loss (UL), pls do
`grep PROJECTION loss_summ_data.tsv | awk '{if ($3 == "I" || $3 == "PI" || $3 == "UL") print $2}' | sort > I_PI_UL.txt
sort -k4,4 query_annotation.bed -o query_annotation.sorted.bed
join -1 1 -2 4 I_PI_UL.txt query_annotation.sorted.bed -t $'\t'  > query_annotation.I_PI_UL.bed`

Afterwards, for certain applications, you could e.g. filter for 1:1 orthologs. 
For codon alignments, we provide a tool documented [here](https://github.com/hillerlab/TOGA/wiki/Building-multiple-codon-alignments). 
And of course, we welcome workflows that users developed and that others could use as well. 

Hope that helps
Michael

**Comment by kirilenkobm** [comment]
To be transferred here: https://github.com/hillerlab/TOGA/wiki/Interpreting-results
