### ISSUE TITLE
Can we run TOGA in separate modules

### ISSUE THREAD

**Issue by DiegoSafian** [hillerlab/TOGA#93]
Hi,

I wonder if it is possible to independently run gene annotation, infer orthologs, and classify genes using TOGA. I would like to only run "classify genes" using a target genome and gene annotation file. 

Thanks in advance,
Diego

**Comment by MichaelHiller** [comment]
Certainly possible, but you would have to subdivide the TOGA code somehow, which right now runs as a full pipeline. 
These things are all coupled: you only know if you have a real ortholog if the gene annotated on an orthologous chain is actually intact. 

Since the CESAR step takes the most time and the rest don't consume much runtime, it might be easier to just keep it as a one pipeline.

**Comment by kirilenkobm** [comment]
Hi @DiegoSafian 

To stop the pipeline right after the chains classification step pls apply the --stop_at_chain_class flag.
